## Advanced Lane Finding Project

The goals / steps of this project are the following:

* Compute the camera calibration matrix and distortion coefficients given a set of chessboard images.
* Apply a distortion correction to raw images.
* Use color transforms, gradients, etc., to create a thresholded binary image.
* Apply a perspective transform to rectify binary image ("birds-eye view").
* Detect lane pixels and fit to find the lane boundary.
* Determine the curvature of the lane and vehicle position with respect to center.
* Warp the detected lane boundaries back onto the original image.
* Output visual display of the lane boundaries and numerical estimation of lane curvature and vehicle position.

---
## First, I'll compute the camera calibration using chessboard images

In [6]:
import numpy as np
import cv2
import glob
import matplotlib.pyplot as plt
%matplotlib qt

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

# Arrays to store object points and image points from all the images.
objpoints = [] # 3d points in real world space
imgpoints = [] # 2d points in image plane.

# Make a list of calibration images
images = glob.glob('../camera_cal/calibration*.jpg')

# Step through the list and search for chessboard corners
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

    # Find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6),None)

    # If found, add object points, image points
    if ret == True:
        objpoints.append(objp)
        imgpoints.append(corners)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, (9,6), corners, ret)
print(img)

[[[184 188 199]
  [ 34  37  45]
  [170 173 177]
  ..., 
  [153 153 153]
  [179 179 179]
  [155 155 155]]

 [[ 81  83  93]
  [ 27  30  38]
  [120 123 127]
  ..., 
  [142 142 142]
  [149 149 149]
  [152 152 152]]

 [[114 115 125]
  [ 29  31  39]
  [136 137 141]
  ..., 
  [133 133 133]
  [131 131 131]
  [146 146 146]]

 ..., 
 [[ 35  27  27]
  [ 98  93  92]
  [123 118 117]
  ..., 
  [129 131 131]
  [130 132 132]
  [132 134 134]]

 [[ 40  32  32]
  [ 71  63  63]
  [117 112 111]
  ..., 
  [131 133 133]
  [139 141 141]
  [127 129 129]]

 [[ 47  39  39]
  [ 30  22  22]
  [ 85  80  79]
  ..., 
  [134 136 136]
  [127 129 129]
  [ 80  82  82]]]


## And so on and so forth...